#!/bin/sh
SHOMEI_USER="shomei"
SHOMEI_PASS="themoney"
SHOMEI_SERVER="https://shomei.herokuapp.com"

status=$(defaults read /private/var/db/.TimeMachine.Results RESULT)

if [ "${status}" = "13" ] || [ "${status}" = "0" ]; then
  status="success"
else
  status="failure"
fi

eval curl --user ${SHOMEI_USER}:${SHOMEI_PASS} -X POST -d \
"'ping={\"machine\":\"${HOSTNAME}\",\"status\":\"${status}\"}'" \
-s ${SHOMEI_SERVER}/pings
